name: holla
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  http: ^1.2.1
  pinput: ^4.0.0
  lucide_icons: ^0.257.0
  easy_localization: ^3.0.1
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  flutter_secure_storage: ^9.1.1
  camera: ^0.11.2
  image_picker: ^1.2.1
  permission_handler: ^11.0.0
  device_info_plus: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/lang/

  fonts:
    - family: CrimsonText
      fonts:
        - asset: assets/fonts/CrimsonText-Regular.ttf
          weight: 400
        - asset: assets/fonts/CrimsonText-Bold.ttf
          weight: 700
        - asset: assets/fonts/CrimsonText-SemiBold.ttf
          weight: 600

    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-Medium.ttf
          weight: 500

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
          weight: 400

    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/app.png"
  remove_alpha_ios: true
